### ISSUE TITLE
Refactoring/smells/misc bugs todo list

### ISSUE THREAD

**Issue by hunterboerner** [rabbit-ci/rabbit-ci#45]
- [x] ~~Some models use integer fields for foreign keys (e.g. project_id). SSHKey uses a proper field type for relationships. I don't know what it's called. Sorry. Just look at the SSHKey migration and compare it with others. (http://www.postgresql.org/docs/8.1/static/tutorial-fk.html).~~ Partial work in #48.
- [x] ~~Logs should not be serialized in the StepSerializer. This is _waaaay_ too slow.~~ This is fast enough now.
- [x] Serializers should be the views. https://github.com/AgilionApps/ja_serializer#phoenix-usage
- [x] `14:24:37.518 [info] RabbitCICore.StepUpdaterChannel received join event with topic "steps:1139" but channel already joined`
