### ISSUE TITLE
Frontend/Misc-todo

### ISSUE THREAD

**Issue by hunterboerner** [rabbit-ci/rabbit-ci#48]
Todo:
- [x] Create stub ember app
- [x] Pretty log output (#50)
- [ ] Log scroll position
- [ ] Javascript warnings
- [x] Log channel join should not use broadcast.
- [x] Log line numbers should not inherit font weight
- [x] Random blank lines in logs. Not sure if vagrant or rabbitci.
- [ ] Log highlight issue (https://github.com/emberjs/ember-collection/issues/111)
- [x] Slashes in project names (breaks URLs)
- [x] **Streaming** Live updating the page using Phoenix channels.
  - [x] Logs
    - [x] Bug: Log order is not always preserved. There is a race condition...
  - [x] Builds
  - [x] When reconnecting after being disconnected, things need to reload (Logs already do this).
- [x] **Test cleanup** Use new test cases and test helpers.
  - [x] Models
    - [x] SSHKeyTest
    - [x] BranchTest
    - [x] BuildTest
    - [x] LogTest
    - [x] StepTest
  - [x] Controllers
    - [x] BranchControllerTest
    - [x] BuildControllerTest
    - [x] ProjectControllerTest
    - [x] IndexControllerTest
  - [x] Remove RabbitCICore.IntegrationCase
  - [x] Remove `alias RabbitCICore.Repo`, `use ...Case` already does this.
- [ ] **Tests** Coverage is lacking. Incomplete list.
  - [ ] Controllers
    - [x] Validate Content-Type is JSON-API (Done by JaSerializer)
  - [ ] Models
    - [x] ProjectTest (Doesn't exist)
    - [x] StepTest
      - [x] Step.log/2 needs testing
- [ ] Update stuff
  - [x] Models
    - [x] `warning: before_insert is deprecated
            web/models/build.ex:10: RabbitCICore.Build (module)`
  - [x] Misc
    - [x] `lib/build_man/vagrant.ex:156: warning: you are piping into a function call without parentheses, which may be ambiguous. Please wrap the function you are piping into in parentheses. For example:`
    - [x] `lib/build_man/git_helpers.ex:54: warning: multiple clauses with default values should define a function head with the defaults, def git/3 has multiple clauses and defines defaults in a clause with a body`
    - [x] `lib/build_man/vagrant.ex:94: warning: clauses for the same def should be grouped together, def handle_info/2 was previously defined (lib/build_man/vagrant.ex:41)`
- [x] Sometimes when I get disconnected from RabbitMQ and reconnect, I am unable to start new builds. Unsure of the cause.
- [ ] We need proper pagination.
- [ ] has_one relationships don't prevent a second record from being created. (unique_index on thing_id ?)
- [ ] GitHelpers: use Keyword lists for options.

**Comment by hunterboerner** [comment]
BuildController index route performance improvements:

(All tested with MIX_ENV=prod)
Before: 120ms
9c745846e8b978fcc517247ac61431e4713c9f6e: 40ms
37265d90b8335e5a0ace1a55259e5cf2d3422067: 15ms
6993d2171ae6c3d551eef2a5da71b22d04fa60b1 (Response is about 2k lines vs 1k, before was 18ms): 12ms

**Comment by hunterboerner** [comment]
- [ ] ff
